# Generated by Django 4.0.1 on 2022-01-27 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='can',
            name='can_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
