# Generated by Django 4.0.1 on 2022-01-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_id_alter_user_name_alter_user_score'),
        ('can', '0003_rename_filled_can_reported_alter_can_can_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can',
            name='can_id',
        ),
        migrations.CreateModel(
            name='BinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
