# Generated by Django 4.0.1 on 2022-01-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0004_remove_can_can_id_binrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='binrequest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
